### ISSUE TITLE
底栏右侧缩进

### ISSUE THREAD

**Issue by lisontowind** [mustakshif/Asri-for-SiYuan#16]
![image](https://github.com/mustakshif/Asri-for-SiYuan/assets/47842345/2d2e2fed-5e95-4165-949e-63bec6303cdd)
大大，我发现了一个可能的问题，如图，如果右侧栏没有图标但折叠侧栏未打开，右侧还是会留有空隙。

**Comment by mustakshif** [comment]
谢谢反馈，我这里复现了，后续会优化下状态栏位移的逻辑

**Comment by mustakshif** [comment]
2.0.3已修复，稍后更新
