### ISSUE TITLE
更新主题，提示失败

### ISSUE THREAD

**Issue by zzz51522** [mustakshif/Asri-for-SiYuan#18]
更新主题，提示失败。尝试多次，都显示这个提示。
![image](https://github.com/mustakshif/Asri-for-SiYuan/assets/145221733/5816f118-6f3c-4fca-b437-b58cd39eae35)

系统：Windows
思源版本：v2.12.6

**Comment by mustakshif** [comment]
我这边Windows和Mac上测试都没问题，要不重启下思源？

**Comment by zzz51522** [comment]
重启思源软件，用代理都无效。最后把主题删了，重新下载解决的（更新提示失败，但重新下载正常）。
