### ISSUE TITLE
能否支持标题栏与页签栏合并

### ISSUE THREAD

**Issue by indevn** [mustakshif/Asri-for-SiYuan#8]
我是一个Windows用户，很喜欢这个主题。
但当顶栏自动隐藏时，关闭和控制窗口会变得困难；当顶栏显示时，空荡荡的顶栏会占用更多的屏幕空间。
能否支持标题栏和页签栏合并，类似rem craft主题的效果？
我相信这会是简洁与易用性的平衡，很期待有相关改进！
![image](https://github.com/mustakshif/Hadeeth-for-SiYuan/assets/11895003/b9d604c5-449e-42ba-b07b-879b1225bf7f)

**Comment by mustakshif** [comment]
感谢提议。

我也想过这个方案，但是目前以我的技术力还无法实现😂；其次对于一些安装了插件的用户，页签空间可能会被大幅挤占，左右分屏的时候右边窗口可能一个页签都显示不完全。

后续我会测试一下把 Windows 的窗口控制按钮独立出来是否可行，这样即使隐藏了顶栏也可以方便地控制窗口。

**Comment by indevn** [comment]
> 感谢提议。
> 
> 我也想过这个方案，但是目前以我的技术力还无法实现😂；其次对于一些安装了插件的用户，页签空间可能会被大幅挤占，左右分屏的时候右边窗口可能一个页签都显示不完全。
> 
> 后续我会测试一下把 Windows 的窗口控制按钮独立出来是否可行，这样即使隐藏了顶栏也可以方便地控制窗口。

对于第二点，我对顶栏的主要需求在于左上角的“同步”“前进”“后退”按钮；出于简洁的需求，我不会允许太多插件按钮显示在顶栏上。
所以我很希望能够保留左上角的按钮，它们的位置也不会妨碍页签栏，就是不知道这是不是普遍需求。
p.s. 主题的更新速度好快hhh很酷的主题，更加坚定了我长期使用这个主题的信心！

**Comment by mustakshif** [comment]
谢谢你对主题的认可hh，这段时间有空所以更新比较频繁。Rem Craft的方案确实很优秀，我后续再学习学习，如果做成了就大版本更新

**Comment by mustakshif** [comment]
2.0 版本已支持顶栏融合，欢迎更新体验
